name: Run Jobs in Containers

on:
  push:
    branches:
      - main
      - dev

jobs:
  container-job:
    name: Run Inside Container
    runs-on: ubuntu-latest

    container:
      image: python:3.11-slim  # You can replace this with any container image
      options: --user root     # Optional: run as root for more permissions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Python version
        run: python --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Run tests
        run: |
          echo "Insert your test command here"
          pip --version
